# .gitpod.yml
image:
  file: .devcontainer/Dockerfile

tasks:
  - name: Setup Python Environment
    command: |
      python3 -m venv .venv
      source .venv/bin/activate
      pip install -r requirements.txt
      echo "✅ Environment ready!"

vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
